name: Create AKS Cluster

on:
  workflow_dispatch:
    inputs:
      create-aks:
        description: 'Create AKS Cluster'
        required: true

jobs:
  create-aks-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: create aks cluster
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: devops_znode
          template: templates/aks.json
          
                
      
                
      
