name: Create EKS Cluster

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  create-eks-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Download eksctl binary
        run: |
          sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | sudo tar xz -C /tmp

      - name: Move eksctl binary to /usr/local/bin
        run: |
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Verify eksctl installation
        run: eksctl version
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Create EKS cluster
        run: |
          eksctl create cluster \
            --name first-demo-cluster \
            --version 1.23 \
            --node-type t3.medium \
            --nodes 1 \
            --region ap-south-1
      
