name: Azure Storage Account Setup

on:
  workflow_dispatch:

jobs:
  setup-storage-account:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Azure CLI
        uses: pietrobolcato/install-azure-cli-action@main


      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Storage Account
        run: |
          az storage account create \
            --name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --location ${{ secrets.AZURE_REGION }} \
            --sku Standard_LRS

      - name: Get Storage Account Key
        id: storage_key
        run: |
          key=$(az storage account keys list --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --query '[0].value' -o tsv)
          echo "::set-output name=key::$key"

      - name: Create Blob Container
        run: az storage container create --name firstdemocontainer --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --account-key ${{ steps.storage_key.outputs.key }}
        
