name: Create AKS Cluster

on:
  workflow_dispatch:  

jobs:
  create-aks-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure subscription
        run: az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Create AKS cluster
        run: |
          az aks create \
            --resource-group devops_znode \
            --name DevopsDemoCluster \
            --node-count 1 \
            --node-vm-size B2ats_v2 \
            --generate-ssh-keys \
            --enable-managed-identity \
            --enable-addons monitoring \
            --kubernetes-version 1.22.0 \
            --location eastus
