name: Delete EKS Cluster

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  delete-eks-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Delete EKS cluster
        run: |
          eksctl delete cluster --name first-demo-cluster --region ap-south-1 --wait

      # Optionally, you may want to verify cluster deletion
      - name: Verify cluster deletion
        run: |
          aws eks --region ap-south-1  describe-cluster --name first-demo-cluster
