name: Delete EKS Cluster

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  delete-eks-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Download eksctl binary
        run: |
          sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | sudo tar xz -C /tmp

      - name: Move eksctl binary to /usr/local/bin
        run: |
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Verify eksctl installation
        run: eksctl version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Delete EKS cluster
        run: |
          eksctl delete cluster --name first-demo-cluster --region ap-south-1 --wait

      

